import { randomUUID } from 'node:crypto'
import { getDatabase } from '../database'
import { MockSocialPublisher } from '../providers/mock-social-publisher'
import { audit } from './data-service'

export function listSchedule(): Record<string,unknown>[] { return getDatabase().prepare(`SELECT sp.id,sp.scheduled_for,sp.status,ci.id content_item_id,ci.title,cv.platform,cv.copy,sa.display_name account_name,(SELECT count(*) FROM publish_attempts pa WHERE pa.scheduled_post_id=sp.id) attempt_count,(SELECT error_message FROM publish_attempts pa WHERE pa.scheduled_post_id=sp.id ORDER BY attempt_number DESC LIMIT 1) error_message,pp.external_url,pp.published_at FROM scheduled_posts sp JOIN content_variants cv ON cv.id=sp.content_variant_id JOIN content_items ci ON ci.id=cv.content_item_id JOIN social_accounts sa ON sa.id=sp.social_account_id LEFT JOIN published_posts pp ON pp.scheduled_post_id=sp.id ORDER BY sp.scheduled_for`).all() as Record<string,unknown>[] }

export function createSchedule(contentItemId:string,scheduledFor:number):Record<string,unknown>[] {
  if(scheduledFor<=Date.now()) throw new Error('Choose a future date and time.')
  const db=getDatabase(), item=db.prepare('SELECT status FROM content_items WHERE id=?').get(contentItemId) as {status:string}|undefined
  if(item?.status!=='approved') throw new Error('Approve this content before scheduling it.')
  const variants=db.prepare('SELECT cv.id,cv.platform,sa.id account_id FROM content_variants cv LEFT JOIN social_accounts sa ON sa.platform=cv.platform AND sa.enabled=1 WHERE cv.content_item_id=?').all(contentItemId) as {id:string;platform:string;account_id:string|null}[]
  const missing=variants.filter(v=>!v.account_id).map(v=>v.platform); if(!variants.length) throw new Error('This content has no platform variants.'); if(missing.length) throw new Error(`Connect these accounts in Settings first: ${missing.join(', ')}.`)
  const now=Date.now(); db.exec('BEGIN IMMEDIATE'); try { const insert=db.prepare('INSERT INTO scheduled_posts (id,content_variant_id,social_account_id,scheduled_for,status,idempotency_key,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)'); for(const v of variants) insert.run(randomUUID(),v.id,v.account_id,scheduledFor,'scheduled',randomUUID(),now,now); db.prepare('UPDATE content_items SET status=?,scheduled_for=?,updated_at=? WHERE id=?').run('scheduled',scheduledFor,now,contentItemId); db.exec('COMMIT') } catch(e){db.exec('ROLLBACK');throw e}
  audit('content.scheduled','content_items',contentItemId,{scheduledFor}); return listSchedule().filter(x=>x.content_item_id===contentItemId)
}

export async function attemptPublish(scheduledPostId:string):Promise<Record<string,unknown>> {
  const db=getDatabase(), row=db.prepare('SELECT sp.*,cv.platform,cv.copy,ci.id content_item_id,ci.status content_status,sa.external_account_id FROM scheduled_posts sp JOIN content_variants cv ON cv.id=sp.content_variant_id JOIN content_items ci ON ci.id=cv.content_item_id JOIN social_accounts sa ON sa.id=sp.social_account_id WHERE sp.id=?').get(scheduledPostId) as Record<string,unknown>|undefined
  if(!row) throw new Error('Scheduled post not found.'); if(row.status==='published') throw new Error('This post is already published.'); if(!['scheduled','failed'].includes(String(row.content_status))) throw new Error('Content must remain scheduled.')
  const attempt=((db.prepare('SELECT max(attempt_number) n FROM publish_attempts WHERE scheduled_post_id=?').get(scheduledPostId) as {n:number|null}).n??0)+1, id=randomUUID(), now=Date.now()
  try { const result=await new MockSocialPublisher(String(row.platform)).publish({idempotencyKey:String(row.idempotency_key),platform:String(row.platform),accountId:String(row.external_account_id),copy:String(row.copy),mediaPaths:[],approved:true}); db.exec('BEGIN IMMEDIATE'); db.prepare('INSERT INTO publish_attempts (id,scheduled_post_id,idempotency_key,attempt_number,status,request_json,response_json,attempted_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run(id,scheduledPostId,String(row.idempotency_key),attempt,'published',JSON.stringify({platform:row.platform}),JSON.stringify(result),now,now,now); db.prepare('UPDATE scheduled_posts SET status=?,updated_at=? WHERE id=?').run('published',now,scheduledPostId); db.prepare('INSERT OR IGNORE INTO published_posts (id,scheduled_post_id,external_post_id,external_url,published_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').run(randomUUID(),scheduledPostId,result.externalPostId,result.externalUrl??null,now,now,now); const remaining=(db.prepare("SELECT count(*) n FROM scheduled_posts sp JOIN content_variants cv ON cv.id=sp.content_variant_id WHERE cv.content_item_id=? AND sp.status!='published'").get(String(row.content_item_id)) as {n:number}).n; if(!remaining) db.prepare('UPDATE content_items SET status=?,updated_at=? WHERE id=?').run('published',now,String(row.content_item_id)); db.exec('COMMIT'); audit('publish.mock.completed','scheduled_posts',scheduledPostId,{attempt}); return listSchedule().find(x=>x.id===scheduledPostId)! } catch(e){ const message=e instanceof Error?e.message:'Mock publishing failed.'; db.prepare('INSERT INTO publish_attempts (id,scheduled_post_id,idempotency_key,attempt_number,status,request_json,error_message,attempted_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run(id,scheduledPostId,String(row.idempotency_key),attempt,'failed',JSON.stringify({platform:row.platform}),message,now,now,now); db.prepare('UPDATE scheduled_posts SET status=?,updated_at=? WHERE id=?').run('failed',now,scheduledPostId); throw e }
}
